import type { Incident } from "@/game/types";

/** Banco aprovado editorialmente em v0.2.1. spawnMinute e definido pelo gerador diario. */
export const caseBank: Incident[] = [
  {
    id: "pool-e-01",
    caseCode: "E-01",
    tier: "easy",
    title: "Resgate em Fachada Comercial",
    district: "Centro",
    priority: "P3",
    reliability: "Alta",
    description: "Um técnico de manutenção ficou preso em uma plataforma externa após falha do mecanismo de sustentação. A área abaixo já foi isolada, mas o equipamento continua cedendo lentamente.",
    recommendedTags: ["resgate", "mobilidade"],
    attributeWeights: { agility: 2, vigor: 1 },
    spawnMinute: 0,
    deadlineMinutes: 95,
    missionDurationMinutes: 48,
    risk: "Baixo",
    minDay: 1,
    weight: 5,
    cooldownDays: 3,
    powerAffinityHeroIds: [],
    effectSuggestion: "Caso introdutório de resgate. Falha/expiração: trabalhador sofre ferimentos e a via permanece interditada por algumas horas.",
    designIntent: "Bom para agente solo com mobilidade; não deve exigir potência.",
  },
  {
    id: "pool-e-02",
    caseCode: "E-02",
    tier: "easy",
    title: "Semáforos Fora de Sincronia",
    district: "Centro",
    priority: "P3",
    reliability: "Alta",
    description: "Uma falha de controle colocou três cruzamentos movimentados em ciclos conflitantes. Já há pequenos acidentes e o trânsito começa a travar.",
    recommendedTags: ["controle", "precisao"],
    attributeWeights: { intelligence: 2, agility: 1 },
    spawnMinute: 0,
    deadlineMinutes: 110,
    missionDurationMinutes: 50,
    risk: "Baixo",
    minDay: 1,
    weight: 5,
    cooldownDays: 3,
    powerAffinityHeroIds: [],
    effectSuggestion: "Sucesso rápido evita congestionamento em cadeia. Expiração: o distrito recebe pressão operacional adicional no restante do turno.",
    designIntent: "Caso de INT/controle para dar espaço a especialistas técnicos.",
  },
  {
    id: "pool-e-03",
    caseCode: "E-03",
    tier: "easy",
    title: "Drone de Carga Desgovernado",
    district: "Norte",
    priority: "P3",
    reliability: "Alta",
    description: "Um drone industrial perdeu navegação e circula em baixa altitude entre galpões. A carga é pesada e pode cair sobre trabalhadores.",
    recommendedTags: ["mobilidade", "precisao", "controle"],
    attributeWeights: { agility: 2, intelligence: 1 },
    spawnMinute: 0,
    deadlineMinutes: 80,
    missionDurationMinutes: 55,
    risk: "Baixo",
    minDay: 1,
    weight: 4,
    cooldownDays: 4,
    powerAffinityHeroIds: [],
    effectSuggestion: "Falha pode danificar infraestrutura leve; sem consequência narrativa fixa.",
    designIntent: "Permite solução solo por AGI alta ou técnica que cubra precisão/controle.",
  },
  {
    id: "pool-e-04",
    caseCode: "E-04",
    tier: "easy",
    title: "Princípio de Incêndio em Oficina",
    district: "Oeste",
    priority: "P3",
    reliability: "Alta",
    description: "Um incêndio pequeno começou em uma oficina mecânica. Funcionários evacuaram, mas cilindros pressurizados permanecem no interior.",
    recommendedTags: ["controle", "resgate", "resistencia"],
    attributeWeights: { vigor: 2, strength: 1 },
    spawnMinute: 0,
    deadlineMinutes: 75,
    missionDurationMinutes: 58,
    risk: "Baixo",
    minDay: 1,
    weight: 5,
    cooldownDays: 3,
    powerAffinityHeroIds: ["helio"],
    effectSuggestion: "Expiração aumenta o risco e transforma o local em perda material relevante; pode gerar mensagem operacional de acompanhamento.",
    designIntent: "Foco VIG: ambiente de calor e risco físico. Hélio pode obter vantagem contextual pelo domínio do fogo/calor, sem transformar INT em requisito principal.",
  },
  {
    id: "pool-e-05",
    caseCode: "E-05",
    tier: "easy",
    title: "Passageiros Presos no Elevador",
    district: "Leste",
    priority: "P3",
    reliability: "Alta",
    description: "Um elevador residencial parou entre andares com quatro passageiros. Uma pessoa relata crise de ansiedade, mas não há sinais de dano estrutural.",
    recommendedTags: ["resgate", "controle"],
    attributeWeights: { intelligence: 2, charisma: 1 },
    spawnMinute: 0,
    deadlineMinutes: 120,
    missionDurationMinutes: 42,
    risk: "Baixo",
    minDay: 1,
    weight: 5,
    cooldownDays: 4,
    powerAffinityHeroIds: [],
    effectSuggestion: "Falha não deve causar lesão grave automaticamente; consequência principal é demora, estresse e reclamação.",
    designIntent: "Caso leve que valoriza CAR como apoio.",
  },
  {
    id: "pool-e-06",
    caseCode: "E-06",
    tier: "easy",
    title: "Vazamento em Hidrante Principal",
    district: "Sul",
    priority: "P3",
    reliability: "Alta",
    description: "Uma ruptura em uma linha de água abriu um jato de alta pressão e começa a alagar uma rua comercial.",
    recommendedTags: ["controle", "contenção", "potencia"],
    attributeWeights: { strength: 2, vigor: 1 },
    spawnMinute: 0,
    deadlineMinutes: 100,
    missionDurationMinutes: 54,
    risk: "Baixo",
    minDay: 1,
    weight: 4,
    cooldownDays: 4,
    powerAffinityHeroIds: ["alexandra"],
    effectSuggestion: "Expiração causa dano material leve e bloqueio temporário de rua.",
    designIntent: "Foco FOR com afinidade de Água: Alexandra deve ter vantagem contextual clara por manipular fluxo e pressão, mesmo sem FOR alto.",
  },
  {
    id: "pool-e-07",
    caseCode: "E-07",
    tier: "easy",
    title: "Animal Preso em Estrutura Elevada",
    district: "Norte",
    priority: "P3",
    reliability: "Alta",
    description: "Um animal de grande porte ficou preso em uma estrutura metálica acima de uma área pública. A multidão dificulta o acesso seguro.",
    recommendedTags: ["resgate", "mobilidade"],
    attributeWeights: { agility: 2, charisma: 1 },
    spawnMinute: 0,
    deadlineMinutes: 125,
    missionDurationMinutes: 45,
    risk: "Baixo",
    minDay: 1,
    weight: 3,
    cooldownDays: 6,
    powerAffinityHeroIds: [],
    effectSuggestion: "Sem efeito persistente; serve como ocorrência de respiro.",
    designIntent: "Tom deliberadamente leve para quebrar sequência de crises.",
  },
  {
    id: "pool-e-08",
    caseCode: "E-08",
    tier: "easy",
    title: "Curto em Subestação de Bairro",
    district: "Leste",
    priority: "P3",
    reliability: "Média",
    description: "Uma subestação local apresenta arcos elétricos intermitentes. Técnicos desligaram parte da rede e aguardam uma janela segura para aproximação.",
    recommendedTags: ["energia", "controle", "precisao"],
    attributeWeights: { vigor: 2, intelligence: 1 },
    spawnMinute: 0,
    deadlineMinutes: 90,
    missionDurationMinutes: 60,
    risk: "Baixo",
    minDay: 1,
    weight: 4,
    cooldownDays: 5,
    powerAffinityHeroIds: ["elysia"],
    effectSuggestion: "Expiração prolonga o apagão local; não deve automaticamente virar crise.",
    designIntent: "Foco VIG, não apenas INT: aproximação sob arcos exige sustentação. Elysia recebe vantagem contextual forte por Energia/condução.",
  },
  {
    id: "pool-e-09",
    caseCode: "E-09",
    tier: "easy",
    title: "Queda de Letreiro sobre Calçada",
    district: "Centro",
    priority: "P3",
    reliability: "Alta",
    description: "Um letreiro de grande porte ficou pendurado por poucos pontos de fixação sobre uma calçada já evacuada.",
    recommendedTags: ["contenção", "resgate"],
    attributeWeights: { strength: 2, vigor: 1 },
    spawnMinute: 0,
    deadlineMinutes: 105,
    missionDurationMinutes: 46,
    risk: "Baixo",
    minDay: 1,
    weight: 4,
    cooldownDays: 4,
    powerAffinityHeroIds: [],
    effectSuggestion: "Falha gera dano material; risco humano baixo se a área continuar isolada.",
    designIntent: "FOR/VIG solo clássico.",
  },
  {
    id: "pool-e-10",
    caseCode: "E-10",
    tier: "easy",
    title: "Pequena Fuga em Galeria de Serviço",
    district: "Oeste",
    priority: "P3",
    reliability: "Média",
    description: "Um invasor foi visto entrando em uma galeria técnica e se recusa a sair. Não há confirmação de arma nem de habilidade especial.",
    recommendedTags: ["reconhecimento", "interceptacao"],
    attributeWeights: { intelligence: 2, agility: 1 },
    spawnMinute: 0,
    deadlineMinutes: 100,
    missionDurationMinutes: 58,
    risk: "Baixo",
    minDay: 1,
    weight: 4,
    cooldownDays: 5,
    powerAffinityHeroIds: [],
    effectSuggestion: "Expiração permite fuga do suspeito; pode registrar uma flag de ocorrência perdida sem consequência de campanha obrigatória.",
    designIntent: "Caso de reconhecimento que não precisa virar combate.",
  },
  {
    id: "pool-e-11",
    caseCode: "E-11",
    tier: "easy",
    title: "Pane em Passarela Móvel",
    district: "Sul",
    priority: "P3",
    reliability: "Alta",
    description: "Uma passarela automatizada travou inclinada com passageiros ainda sobre a estrutura. O sistema de emergência não responde.",
    recommendedTags: ["resgate", "controle", "potencia"],
    attributeWeights: { strength: 2, charisma: 1 },
    spawnMinute: 0,
    deadlineMinutes: 95,
    missionDurationMinutes: 50,
    risk: "Baixo",
    minDay: 1,
    weight: 4,
    cooldownDays: 4,
    powerAffinityHeroIds: [],
    effectSuggestion: "Falha causa ferimentos leves e interdição; sucesso preserva fluxo do terminal.",
    designIntent: "Foco FOR/CAR: estabilizar fisicamente a passarela e manter passageiros coordenados; evita repetir solução puramente técnica.",
  },
  {
    id: "pool-e-12",
    caseCode: "E-12",
    tier: "easy",
    title: "Tumulto em Praça de Alimentação",
    district: "Leste",
    priority: "P3",
    reliability: "Média",
    description: "Uma discussão entre grupos cresceu e o pânico se espalha após rumores de uma ameaça inexistente. Segurança local pede apoio antes que haja pisoteamento.",
    recommendedTags: ["controle", "resgate"],
    attributeWeights: { charisma: 2, intelligence: 1 },
    spawnMinute: 0,
    deadlineMinutes: 70,
    missionDurationMinutes: 44,
    risk: "Baixo",
    minDay: 1,
    weight: 4,
    cooldownDays: 5,
    powerAffinityHeroIds: [],
    effectSuggestion: "Falha aumenta feridos leves e tensão local; bom gancho para mensagens reativas no NEXO operacional.",
    designIntent: "Caso social para CAR ter utilidade clara.",
  },
  {
    id: "inc-002",
    caseCode: "M-01",
    tier: "medium",
    title: "Perseguição na Linha Norte",
    district: "Norte",
    priority: "P2",
    reliability: "Alta",
    description: "Suspeito com habilidade desconhecida foge por vias elevadas e muda de rota constantemente.",
    recommendedTags: ["velocidade", "interceptacao", "mobilidade"],
    attributeWeights: { agility: 3, intelligence: 2, vigor: 1 },
    spawnMinute: 0,
    deadlineMinutes: 62,
    missionDurationMinutes: 72,
    risk: "Médio",
    minDay: 1,
    weight: 4,
    cooldownDays: 5,
    powerAffinityHeroIds: [],
    effectSuggestion: "Manter como caso móvel de perseguição. Expiração: suspeito escapa.",
    designIntent: "Caso atual do protótipo; texto preservado para avaliação.",
  },
  {
    id: "inc-004",
    caseCode: "M-02",
    tier: "medium",
    title: "Pane Energética no Hospital",
    district: "Centro",
    priority: "P2",
    reliability: "Baixa",
    description: "Oscilações elétricas afetaram equipamentos críticos. O gerador auxiliar também apresenta comportamento irregular.",
    recommendedTags: ["energia", "precisao", "controle"],
    attributeWeights: { intelligence: 3, agility: 1, vigor: 1 },
    spawnMinute: 0,
    deadlineMinutes: 76,
    missionDurationMinutes: 84,
    risk: "Médio",
    minDay: 1,
    weight: 3,
    cooldownDays: 7,
    powerAffinityHeroIds: [],
    effectSuggestion: "Expiração pode aumentar o custo humano do incidente; deve continuar sem exigir dano narrativo específico até autoria final.",
    designIntent: "Caso atual; excelente para testar técnicas de energia/precisão.",
  },
  {
    id: "inc-006",
    caseCode: "M-03",
    tier: "medium",
    title: "Enchente na Baixada Leste",
    district: "Leste",
    priority: "P2",
    reliability: "Alta",
    description: "A água sobe rapidamente e moradores estão isolados em telhados. A correnteza dificulta aproximação terrestre.",
    recommendedTags: ["resgate", "mobilidade", "controle"],
    attributeWeights: { vigor: 2, agility: 2, intelligence: 2 },
    spawnMinute: 0,
    deadlineMinutes: 94,
    missionDurationMinutes: 126,
    risk: "Médio",
    minDay: 1,
    weight: 3,
    cooldownDays: 7,
    powerAffinityHeroIds: ["alexandra"],
    effectSuggestion: "Falha/expiração amplia número de civis isolados e dano material.",
    designIntent: "Caso atual; multiatributo equilibrado.",
  },
  {
    id: "inc-007",
    caseCode: "M-04",
    tier: "medium",
    title: "Ataque ao Depósito Municipal",
    district: "Norte",
    priority: "P3",
    reliability: "Média",
    description: "Invasores super-humanos tentam roubar artefatos apreendidos. O objetivo exato ainda não está claro.",
    recommendedTags: ["combate", "potencia", "reconhecimento"],
    attributeWeights: { strength: 3, intelligence: 2, vigor: 2 },
    spawnMinute: 0,
    deadlineMinutes: 110,
    missionDurationMinutes: 92,
    risk: "Médio",
    minDay: 2,
    weight: 2,
    cooldownDays: 9,
    powerAffinityHeroIds: [],
    effectSuggestion: "Falha permite roubo de material apreendido; consequência futura opcional via flag.",
    designIntent: "Caso atual. “Artefatos” já existe no texto do protótipo; revisar se permanece na versão final.",
  },
  {
    id: "pool-m-05",
    caseCode: "M-05",
    tier: "medium",
    title: "Incêndio em Estacionamento Subterrâneo",
    district: "Centro",
    priority: "P2",
    reliability: "Alta",
    description: "Fogo e fumaça se espalham por dois níveis de estacionamento. Há veículos abandonados e possibilidade de pessoas desorientadas na fumaça.",
    recommendedTags: ["resgate", "controle", "resistencia"],
    attributeWeights: { vigor: 3, charisma: 2, intelligence: 1 },
    spawnMinute: 0,
    deadlineMinutes: 72,
    missionDurationMinutes: 86,
    risk: "Médio",
    minDay: 1,
    weight: 4,
    cooldownDays: 5,
    powerAffinityHeroIds: ["yuki"],
    effectSuggestion: "Falha aumenta danos e pode elevar desgaste dos agentes por ambiente hostil.",
    designIntent: "Foco VIG/CAR: operar sob fumaça e orientar civis desorientados. Yuki pode ter vantagem contextual de Frio/controle térmico.",
  },
  {
    id: "pool-m-06",
    caseCode: "M-06",
    tier: "medium",
    title: "Colisão em Viaduto de Carga",
    district: "Oeste",
    priority: "P2",
    reliability: "Alta",
    description: "Dois caminhões colidiram e um deles ameaça atravessar a proteção lateral do viaduto. O trânsito está parado nos dois sentidos.",
    recommendedTags: ["contenção", "resgate", "potencia"],
    attributeWeights: { strength: 3, vigor: 2, intelligence: 1 },
    spawnMinute: 0,
    deadlineMinutes: 68,
    missionDurationMinutes: 82,
    risk: "Médio",
    minDay: 1,
    weight: 4,
    cooldownDays: 5,
    powerAffinityHeroIds: [],
    effectSuggestion: "Expiração pode causar queda do veículo e ampliar o incidente.",
    designIntent: "FOR/VIG com oportunidade para potência.",
  },
  {
    id: "pool-m-07",
    caseCode: "M-07",
    tier: "medium",
    title: "Sabotagem em Torre de Comunicação",
    district: "Norte",
    priority: "P2",
    reliability: "Média",
    description: "Uma torre de comunicação apresenta falhas simultâneas e sinais de acesso não autorizado. Ainda não se sabe se o objetivo é roubo, sabotagem ou distração.",
    recommendedTags: ["reconhecimento", "precisao", "interceptacao"],
    attributeWeights: { charisma: 2, intelligence: 2, agility: 1 },
    spawnMinute: 0,
    deadlineMinutes: 88,
    missionDurationMinutes: 78,
    risk: "Médio",
    minDay: 2,
    weight: 3,
    cooldownDays: 7,
    powerAffinityHeroIds: [],
    effectSuggestion: "Falha reduz comunicação local por algumas horas e pode afetar ambientação do turno.",
    designIntent: "Foco CAR/INT: coordenação com técnicos e leitura do ataque importam tanto quanto perseguição. Abre espaço para heróis menos ágeis.",
  },
  {
    id: "pool-m-08",
    caseCode: "M-08",
    tier: "medium",
    title: "Passarela Estrutural em Colapso",
    district: "Sul",
    priority: "P2",
    reliability: "Alta",
    description: "Uma passarela de pedestres sofreu ruptura em um dos apoios. Há pessoas em ambos os lados e duas ainda estão sobre a estrutura.",
    recommendedTags: ["resgate", "contenção", "mobilidade"],
    attributeWeights: { strength: 2, agility: 2, vigor: 2 },
    spawnMinute: 0,
    deadlineMinutes: 58,
    missionDurationMinutes: 74,
    risk: "Médio",
    minDay: 1,
    weight: 4,
    cooldownDays: 6,
    powerAffinityHeroIds: [],
    effectSuggestion: "Prazo curto; falha aumenta ferimentos e bloqueia acesso local.",
    designIntent: "Caso compacto que pode pedir dupla se nenhum agente cobrir FOR+AGI.",
  },
  {
    id: "pool-m-09",
    caseCode: "M-09",
    tier: "medium",
    title: "Roubo em Movimento na Avenida Sul",
    district: "Sul",
    priority: "P2",
    reliability: "Média",
    description: "Um veículo blindado roubado atravessa avenidas em alta velocidade. O motorista evita bloqueios e pode ter apoio externo.",
    recommendedTags: ["velocidade", "interceptacao", "precisao"],
    attributeWeights: { agility: 3, intelligence: 2, strength: 1 },
    spawnMinute: 0,
    deadlineMinutes: 55,
    missionDurationMinutes: 70,
    risk: "Médio",
    minDay: 2,
    weight: 4,
    cooldownDays: 6,
    powerAffinityHeroIds: [],
    effectSuggestion: "Expiração encerra perseguição com fuga; falha pode causar dano urbano moderado.",
    designIntent: "Favorável a especialista rápido.",
  },
  {
    id: "pool-m-10",
    caseCode: "M-10",
    tier: "medium",
    title: "Evacuação de Escola por Vazamento",
    district: "Leste",
    priority: "P2",
    reliability: "Baixa",
    description: "Professores relatam odor forte e irritação em parte de uma escola. A origem ainda não foi localizada e há informação conflitante sobre quantas salas foram afetadas.",
    recommendedTags: ["resgate", "reconhecimento", "controle"],
    attributeWeights: { charisma: 3, vigor: 2, intelligence: 1 },
    spawnMinute: 0,
    deadlineMinutes: 78,
    missionDurationMinutes: 88,
    risk: "Médio",
    minDay: 2,
    weight: 3,
    cooldownDays: 8,
    powerAffinityHeroIds: [],
    effectSuggestion: "Falha amplia evacuação e número de pessoas expostas; risco permanece genérico até conteúdo final.",
    designIntent: "Foco CAR/VIG: evacuação de crianças, professores e pessoas irritadas/expostas. Inteligência ajuda, mas manejo humano é o centro.",
  },
  {
    id: "pool-m-11",
    caseCode: "M-11",
    tier: "medium",
    title: "Conflito Super-Humano em Via Residencial",
    district: "Oeste",
    priority: "P2",
    reliability: "Média",
    description: "Dois indivíduos com capacidades incomuns entraram em confronto em uma rua residencial. Moradores ainda estão saindo das casas próximas.",
    recommendedTags: ["controle", "combate", "resgate"],
    attributeWeights: { charisma: 3, strength: 2, vigor: 2 },
    spawnMinute: 0,
    deadlineMinutes: 64,
    missionDurationMinutes: 84,
    risk: "Médio",
    minDay: 2,
    weight: 3,
    cooldownDays: 8,
    powerAffinityHeroIds: ["eros"],
    effectSuggestion: "Falha aumenta dano material e risco a civis. Sucesso pode ser alcançado por contenção sem derrotar ninguém.",
    designIntent: "Foco CAR: conter/esfriar o confronto antes de vencer pela força. Eros ganha espaço natural por presença social e controle de área.",
  },
  {
    id: "pool-m-12",
    caseCode: "M-12",
    tier: "medium",
    title: "Falha de Bombas na Estação de Drenagem",
    district: "Leste",
    priority: "P2",
    reliability: "Alta",
    description: "Bombas de drenagem pararam durante chuva forte. A água começa a retornar para túneis de serviço e garagens próximas.",
    recommendedTags: ["controle", "energia", "potencia"],
    attributeWeights: { intelligence: 3, strength: 2, vigor: 1 },
    spawnMinute: 0,
    deadlineMinutes: 82,
    missionDurationMinutes: 92,
    risk: "Médio",
    minDay: 2,
    weight: 3,
    cooldownDays: 7,
    powerAffinityHeroIds: ["alexandra"],
    effectSuggestion: "Expiração pode promover uma ocorrência futura de enchente se o sistema de encadeamento for aprovado.",
    designIntent: "Bom candidato a cadeia de eventos, mas cadeia não é requisito para primeira implementação.",
  },
  {
    id: "inc-001",
    caseCode: "H-01",
    tier: "hard",
    title: "Incêndio no Edifício Aurora",
    district: "Centro",
    priority: "P1",
    reliability: "Média",
    description: "Fumaça densa no 7º andar. Civis ainda podem estar presos e a estrutura começou a apresentar deformações pelo calor.",
    recommendedTags: ["resgate", "controle", "mobilidade"],
    attributeWeights: { intelligence: 3, vigor: 2, agility: 2 },
    spawnMinute: 0,
    deadlineMinutes: 54,
    missionDurationMinutes: 96,
    risk: "Alto",
    minDay: 2,
    weight: 3,
    cooldownDays: 8,
    powerAffinityHeroIds: [],
    effectSuggestion: "Falha/expiração aumenta vítimas e dano estrutural. Deve permanecer ocorrência de alta urgência.",
    designIntent: "Caso atual do protótipo.",
  },
  {
    id: "inc-003",
    caseCode: "H-02",
    tier: "hard",
    title: "Desabamento no Mercado Velho",
    district: "Oeste",
    priority: "P1",
    reliability: "Alta",
    description: "Parte da cobertura cedeu durante horário de pico. Há pessoas soterradas e risco de novos colapsos.",
    recommendedTags: ["resgate", "contenção", "resistencia"],
    attributeWeights: { strength: 3, vigor: 3, intelligence: 1 },
    spawnMinute: 0,
    deadlineMinutes: 70,
    missionDurationMinutes: 118,
    risk: "Alto",
    minDay: 2,
    weight: 3,
    cooldownDays: 9,
    powerAffinityHeroIds: [],
    effectSuggestion: "Falha eleva o número de soterrados e pode prolongar indisponibilidade da área.",
    designIntent: "Caso atual; forte identidade FOR/VIG.",
  },
  {
    id: "inc-005",
    caseCode: "H-03",
    tier: "hard",
    title: "Reféns no Terminal Sul",
    district: "Sul",
    priority: "P1",
    reliability: "Média",
    description: "Grupo armado mantém passageiros em uma plataforma subterrânea. Há relatos conflitantes sobre a quantidade de agressores.",
    recommendedTags: ["interceptacao", "controle", "precisao"],
    attributeWeights: { intelligence: 3, charisma: 2, agility: 2 },
    spawnMinute: 0,
    deadlineMinutes: 58,
    missionDurationMinutes: 105,
    risk: "Alto",
    minDay: 3,
    weight: 2,
    cooldownDays: 10,
    powerAffinityHeroIds: [],
    effectSuggestion: "Falha tem custo humano alto. Expiração representa perda de janela tática, não solução automática.",
    designIntent: "Caso atual; bom para INT/CAR/AGI.",
  },
  {
    id: "inc-008",
    caseCode: "H-04",
    tier: "hard",
    title: "Trem Elevado Fora de Controle",
    district: "Centro",
    priority: "P1",
    reliability: "Alta",
    description: "Uma composição sem frenagem se aproxima de duas estações lotadas. O tempo de intervenção é curto.",
    recommendedTags: ["mobilidade", "controle", "potencia"],
    attributeWeights: { agility: 3, intelligence: 3, strength: 1 },
    spawnMinute: 0,
    deadlineMinutes: 48,
    missionDurationMinutes: 90,
    risk: "Alto",
    minDay: 3,
    weight: 2,
    cooldownDays: 12,
    powerAffinityHeroIds: [],
    effectSuggestion: "Prazo extremamente curto; falha representa impacto grave e deve ser rara.",
    designIntent: "Caso atual; forte candidato a ocorrência de pico.",
  },
  {
    id: "inc-009",
    caseCode: "H-05",
    tier: "hard",
    title: "Evacuação da Torre Prisma",
    district: "Oeste",
    priority: "P2",
    reliability: "Baixa",
    description: "Alarme estrutural e relatos conflitantes apontam uma anomalia no subsolo. Parte dos ocupantes se recusa a evacuar.",
    recommendedTags: ["resgate", "reconhecimento", "contenção"],
    attributeWeights: { intelligence: 3, charisma: 2, vigor: 1 },
    spawnMinute: 0,
    deadlineMinutes: 88,
    missionDurationMinutes: 108,
    risk: "Médio",
    minDay: 3,
    weight: 2,
    cooldownDays: 10,
    powerAffinityHeroIds: [],
    effectSuggestion: "Falha pode deixar civis no prédio e manter a origem da anomalia desconhecida.",
    designIntent: "Caso atual. “Anomalia” deve ser revisada editorialmente no conteúdo final.",
  },
  {
    id: "inc-010",
    caseCode: "H-06",
    tier: "hard",
    title: "Confronto na Praça Cívica",
    district: "Centro",
    priority: "P1",
    reliability: "Média",
    description: "Dois super-humanos em conflito colocam civis e prédios públicos em risco. A multidão dificulta uma resposta agressiva.",
    recommendedTags: ["controle", "combate", "resgate"],
    attributeWeights: { charisma: 2, intelligence: 2, strength: 2, agility: 1 },
    spawnMinute: 0,
    deadlineMinutes: 68,
    missionDurationMinutes: 96,
    risk: "Alto",
    minDay: 3,
    weight: 2,
    cooldownDays: 10,
    powerAffinityHeroIds: [],
    effectSuggestion: "Falha aumenta dano material e vítimas; sucesso não exige necessariamente combate.",
    designIntent: "Caso atual; multiatributo e bom para dupla complementar.",
  },
  {
    id: "pool-h-07",
    caseCode: "H-07",
    tier: "hard",
    title: "Colapso Parcial de Ponte Urbana",
    district: "Norte",
    priority: "P1",
    reliability: "Alta",
    description: "Um trecho de ponte cedeu após impacto pesado. Veículos estão presos em uma seção instável e a estrutura continua movimentando.",
    recommendedTags: ["contenção", "resgate", "potencia", "resistencia"],
    attributeWeights: { strength: 3, vigor: 3, charisma: 1 },
    spawnMinute: 0,
    deadlineMinutes: 52,
    missionDurationMinutes: 112,
    risk: "Alto",
    minDay: 3,
    weight: 2,
    cooldownDays: 10,
    powerAffinityHeroIds: ["demetria"],
    effectSuggestion: "Falha/expiração pode causar queda adicional. Alto desgaste físico sugerido.",
    designIntent: "Foco FOR/VIG e afinidade de Terra: Demétria deve ter vantagem contextual forte por sustentação, barreiras e leitura estrutural.",
  },
  {
    id: "pool-h-08",
    caseCode: "H-08",
    tier: "hard",
    title: "Incêndio Industrial com Equipe Presa",
    district: "Norte",
    priority: "P1",
    reliability: "Média",
    description: "Um incêndio industrial isolou trabalhadores em uma seção interna. Há focos em múltiplos níveis e visibilidade quase nula.",
    recommendedTags: ["resgate", "controle", "resistencia"],
    attributeWeights: { vigor: 3, strength: 2, charisma: 1 },
    spawnMinute: 0,
    deadlineMinutes: 60,
    missionDurationMinutes: 116,
    risk: "Alto",
    minDay: 3,
    weight: 2,
    cooldownDays: 9,
    powerAffinityHeroIds: ["helio"],
    effectSuggestion: "Falha aumenta exposição e desgaste; pode impor custo extra de Energia se futuramente aprovado.",
    designIntent: "Foco VIG/FOR: entrada prolongada em ambiente hostil e retirada de trabalhadores. Hélio pode ter vantagem contextual ligada a fogo/calor.",
  },
  {
    id: "pool-h-09",
    caseCode: "H-09",
    tier: "hard",
    title: "Interferência Energética em Área Comercial",
    district: "Leste",
    priority: "P1",
    reliability: "Baixa",
    description: "Descargas de origem incerta afetam uma quadra inteira, desligando sistemas e causando arcos entre estruturas metálicas. A fonte não foi localizada.",
    recommendedTags: ["energia", "reconhecimento", "controle", "resistencia"],
    attributeWeights: { vigor: 3, intelligence: 2, strength: 1 },
    spawnMinute: 0,
    deadlineMinutes: 66,
    missionDurationMinutes: 104,
    risk: "Alto",
    minDay: 3,
    weight: 2,
    cooldownDays: 11,
    powerAffinityHeroIds: ["elysia"],
    effectSuggestion: "Falha mantém a área evacuada e pode gerar segunda ocorrência de infraestrutura.",
    designIntent: "Foco VIG com afinidade elétrica: Elysia recebe vantagem contextual forte por Energia/condução; INT ajuda a localizar a fonte, mas não domina o caso.",
  },
  {
    id: "pool-h-10",
    caseCode: "H-10",
    tier: "hard",
    title: "Comboio Médico Sob Ataque",
    district: "Sul",
    priority: "P1",
    reliability: "Média",
    description: "Um comboio médico em deslocamento foi bloqueado e está sob ameaça. Há pacientes que não podem permanecer parados por muito tempo.",
    recommendedTags: ["interceptacao", "combate", "resgate"],
    attributeWeights: { agility: 3, strength: 2, intelligence: 2 },
    spawnMinute: 0,
    deadlineMinutes: 50,
    missionDurationMinutes: 92,
    risk: "Alto",
    minDay: 4,
    weight: 2,
    cooldownDays: 11,
    powerAffinityHeroIds: [],
    effectSuggestion: "Falha compromete transporte dos pacientes; prazo deve pressionar decisão rápida.",
    designIntent: "Mistura combate e proteção, sem exigir trio por regra.",
  },
  {
    id: "pool-h-11",
    caseCode: "H-11",
    tier: "hard",
    title: "Falha Estrutural em Torre Residencial",
    district: "Oeste",
    priority: "P1",
    reliability: "Média",
    description: "Moradores relatam estalos, rachaduras recentes e deslocamento visível em uma torre residencial. A evacuação começou, mas ainda há pessoas nos andares superiores.",
    recommendedTags: ["resgate", "contenção", "resistencia"],
    attributeWeights: { strength: 3, vigor: 3, intelligence: 1 },
    spawnMinute: 0,
    deadlineMinutes: 62,
    missionDurationMinutes: 120,
    risk: "Alto",
    minDay: 4,
    weight: 2,
    cooldownDays: 12,
    powerAffinityHeroIds: ["demetria"],
    effectSuggestion: "Falha pode transformar o caso em crise estrutural; encadeamento opcional.",
    designIntent: "Foco FOR/VIG e afinidade estrutural: Demétria é especialmente indicada por Terra, sustentação e leitura estrutural.",
  },
  {
    id: "pool-h-12",
    caseCode: "H-12",
    tier: "hard",
    title: "Fuga de Super-Humano em Túnel Metropolitano",
    district: "Centro",
    priority: "P1",
    reliability: "Baixa",
    description: "Um suspeito com capacidade desconhecida entrou em túneis de manutenção. Trens continuam circulando em trechos adjacentes e equipes civis foram retiradas.",
    recommendedTags: ["reconhecimento", "interceptacao", "mobilidade"],
    attributeWeights: { agility: 3, intelligence: 3, vigor: 1 },
    spawnMinute: 0,
    deadlineMinutes: 56,
    missionDurationMinutes: 100,
    risk: "Alto",
    minDay: 4,
    weight: 2,
    cooldownDays: 10,
    powerAffinityHeroIds: [],
    effectSuggestion: "Expiração permite fuga; falha pode causar dano à rede de transporte.",
    designIntent: "Caso de caça tática, favorece especialistas de mobilidade.",
  },
  {
    id: "pool-c-01",
    caseCode: "C-01",
    tier: "crisis",
    title: "Falha em Cascata na Rede Elétrica Central",
    district: "Centro",
    priority: "P1",
    reliability: "Baixa",
    description: "Subestações entram em desligamento sequencial e sistemas críticos alternam para reserva. Hospital, metrô e sinalização começam a disputar capacidade de emergência.",
    recommendedTags: ["energia", "controle", "precisao", "reconhecimento"],
    attributeWeights: { intelligence: 3, agility: 2, vigor: 2 },
    spawnMinute: 0,
    deadlineMinutes: 46,
    missionDurationMinutes: 132,
    risk: "Alto",
    minDay: 6,
    weight: 1,
    cooldownDays: 18,
    powerAffinityHeroIds: [],
    effectSuggestion: "Crise de infraestrutura. Falha pode gerar 1–2 chamados derivados no mesmo turno se o sistema de encadeamento for aprovado.",
    designIntent: "Crise técnica; não deve aparecer em dia de respiro.",
  },
  {
    id: "pool-c-02",
    caseCode: "C-02",
    tier: "crisis",
    title: "Colisão Iminente na Rede de Trens",
    district: "Centro",
    priority: "P1",
    reliability: "Alta",
    description: "Uma falha de sinalização colocou duas composições em trajetórias conflitantes. Equipes da rede tentam reduzir velocidade, mas a margem está se fechando.",
    recommendedTags: ["controle", "mobilidade", "potencia", "precisao"],
    attributeWeights: { intelligence: 3, agility: 3, strength: 2 },
    spawnMinute: 0,
    deadlineMinutes: 38,
    missionDurationMinutes: 108,
    risk: "Alto",
    minDay: 6,
    weight: 1,
    cooldownDays: 20,
    powerAffinityHeroIds: [],
    effectSuggestion: "Prazo mínimo e consequência severa. Deve ser rara e claramente sinalizada como crise.",
    designIntent: "Versão de crise do trem fora de controle; usar uma ou outra no mesmo ciclo, não ambas próximas.",
  },
  {
    id: "pool-c-03",
    caseCode: "C-03",
    tier: "crisis",
    title: "Incêndio em Múltiplos Blocos",
    district: "Oeste",
    priority: "P1",
    reliability: "Média",
    description: "Ventos fortes espalharam focos de incêndio entre prédios próximos. Bombeiros trabalham em vários pontos, mas duas frentes ameaçam se unir.",
    recommendedTags: ["resgate", "controle", "potencia", "resistencia"],
    attributeWeights: { vigor: 3, strength: 3, charisma: 2, intelligence: 1 },
    spawnMinute: 0,
    deadlineMinutes: 48,
    missionDurationMinutes: 138,
    risk: "Alto",
    minDay: 6,
    weight: 1,
    cooldownDays: 18,
    powerAffinityHeroIds: ["yuki", "helio"],
    effectSuggestion: "Pode ocupar equipe por longo período e pressionar disponibilidade do roster.",
    designIntent: "Crise VIG/FOR: conter frentes e sustentar evacuação prolongada. Yuki e Hélio podem receber vantagens contextuais diferentes ligadas ao controle térmico.",
  },
  {
    id: "pool-c-04",
    caseCode: "C-04",
    tier: "crisis",
    title: "Rompimento de Barreira de Contenção de Água",
    district: "Leste",
    priority: "P1",
    reliability: "Alta",
    description: "Uma barreira de contenção cedeu parcialmente durante chuva intensa. Água avança para uma área densamente ocupada e rotas de evacuação começam a desaparecer.",
    recommendedTags: ["resgate", "contenção", "mobilidade", "controle"],
    attributeWeights: { strength: 3, vigor: 3, charisma: 2 },
    spawnMinute: 0,
    deadlineMinutes: 44,
    missionDurationMinutes: 142,
    risk: "Alto",
    minDay: 6,
    weight: 1,
    cooldownDays: 20,
    powerAffinityHeroIds: ["alexandra"],
    effectSuggestion: "Falha amplia alagamento e pode gerar ocorrências secundárias de resgate.",
    designIntent: "Crise de Água: Alexandra deve receber vantagem contextual muito forte por fluxo, pressão e leitura hidráulica; FOR/VIG ainda importam para contenção física.",
  },
  {
    id: "pool-c-05",
    caseCode: "C-05",
    tier: "crisis",
    title: "Confronto Coordenado em Área Cívica",
    district: "Centro",
    priority: "P1",
    reliability: "Baixa",
    description: "Vários indivíduos super-humanos agem em pontos próximos, forçando evacuação simultânea de ruas e prédios públicos. Não está claro se todos fazem parte do mesmo grupo.",
    recommendedTags: ["combate", "controle", "reconhecimento", "resgate"],
    attributeWeights: { intelligence: 3, charisma: 2, strength: 2, agility: 2 },
    spawnMinute: 0,
    deadlineMinutes: 50,
    missionDurationMinutes: 130,
    risk: "Alto",
    minDay: 7,
    weight: 1,
    cooldownDays: 20,
    powerAffinityHeroIds: [],
    effectSuggestion: "Pressiona composição e informação imperfeita. Falha pode deixar um dos focos escapar.",
    designIntent: "Não definir organização ou motivação antes da autoria final.",
  },
  {
    id: "pool-c-06",
    caseCode: "C-06",
    tier: "crisis",
    title: "Colapso em Complexo de Eventos",
    district: "Sul",
    priority: "P1",
    reliability: "Alta",
    description: "Parte da cobertura de um complexo de eventos cedeu durante evacuação. Há múltiplos bolsões de pessoas presas e risco de novos deslocamentos estruturais.",
    recommendedTags: ["resgate", "contenção", "resistencia", "potencia"],
    attributeWeights: { strength: 3, vigor: 3, charisma: 2 },
    spawnMinute: 0,
    deadlineMinutes: 52,
    missionDurationMinutes: 150,
    risk: "Alto",
    minDay: 7,
    weight: 1,
    cooldownDays: 22,
    powerAffinityHeroIds: ["demetria"],
    effectSuggestion: "Longa duração e alto custo de oportunidade. Falha aumenta número de vítimas.",
    designIntent: "Crise estrutural centrada em FOR/VIG. Demétria deve ter vantagem contextual forte; CAR ajuda a organizar evacuação e equipes civis.",
  },
  {
    id: "pool-c-07",
    caseCode: "C-07",
    tier: "crisis",
    title: "Interrupção Total no Terminal Sul",
    district: "Sul",
    priority: "P1",
    reliability: "Média",
    description: "Energia, sinalização e acessos do terminal falharam quase ao mesmo tempo durante horário de pico. Passageiros se acumulam enquanto equipes relatam sinais de sabotagem.",
    recommendedTags: ["controle", "energia", "reconhecimento", "resgate"],
    attributeWeights: { charisma: 3, vigor: 2, intelligence: 2 },
    spawnMinute: 0,
    deadlineMinutes: 54,
    missionDurationMinutes: 136,
    risk: "Alto",
    minDay: 6,
    weight: 1,
    cooldownDays: 18,
    powerAffinityHeroIds: ["elysia", "eros"],
    effectSuggestion: "Mistura infraestrutura e controle de multidão. Expiração pode gerar tumulto e interrupção prolongada.",
    designIntent: "Crise CAR: controlar fluxo humano é parte central. Elysia tem vantagem contextual na pane elétrica; Eros, na evacuação e coordenação de multidão.",
  },
  {
    id: "pool-c-08",
    caseCode: "C-08",
    tier: "crisis",
    title: "Acidente em Cadeia no Viaduto Norte",
    district: "Norte",
    priority: "P1",
    reliability: "Alta",
    description: "Uma colisão em cadeia envolveu vários veículos e bloqueou todas as faixas. Um veículo pesado está apoiado parcialmente na proteção lateral e há vítimas em pontos diferentes.",
    recommendedTags: ["resgate", "contenção", "potencia", "mobilidade"],
    attributeWeights: { strength: 3, vigor: 3, charisma: 2 },
    spawnMinute: 0,
    deadlineMinutes: 50,
    missionDurationMinutes: 128,
    risk: "Alto",
    minDay: 6,
    weight: 1,
    cooldownDays: 18,
    powerAffinityHeroIds: [],
    effectSuggestion: "Alta demanda física e múltiplas frentes; excelente para testar especialista + apoio.",
    designIntent: "Crise física FOR/VIG: estabilização e retirada pesada. Mobilidade continua útil como capacidade, sem fazer AGI dominar os requisitos.",
  },
  {
    id: "pool-c-09",
    caseCode: "C-09",
    tier: "crisis",
    title: "Pane Generalizada em Hospital de Referência",
    district: "Centro",
    priority: "P1",
    reliability: "Média",
    description: "Sistemas elétricos, elevadores e parte da distribuição interna falharam quase simultaneamente. Equipes médicas operam em contingência e pacientes precisam ser redistribuídos.",
    recommendedTags: ["energia", "controle", "resgate", "precisao"],
    attributeWeights: { charisma: 3, vigor: 3, intelligence: 2 },
    spawnMinute: 0,
    deadlineMinutes: 48,
    missionDurationMinutes: 144,
    risk: "Alto",
    minDay: 7,
    weight: 1,
    cooldownDays: 22,
    powerAffinityHeroIds: ["elysia", "alexandra"],
    effectSuggestion: "Falha tem custo humano elevado, mas detalhes finais dependem da autoria.",
    designIntent: "Crise de suporte: redistribuição de pacientes e coordenação humana ganham peso. Elysia tem vantagem elétrica; Alexandra pode contribuir em resgate/controle fino.",
  },
  {
    id: "pool-c-10",
    caseCode: "C-10",
    tier: "crisis",
    title: "Desabamento em Túnel de Transporte",
    district: "Oeste",
    priority: "P1",
    reliability: "Baixa",
    description: "Um túnel sofreu desabamento em dois pontos, isolando veículos e equipes de manutenção. Sensores indicam movimentação adicional no terreno.",
    recommendedTags: ["resgate", "contenção", "reconhecimento", "resistencia"],
    attributeWeights: { strength: 3, vigor: 3, charisma: 1 },
    spawnMinute: 0,
    deadlineMinutes: 56,
    missionDurationMinutes: 152,
    risk: "Alto",
    minDay: 7,
    weight: 1,
    cooldownDays: 20,
    powerAffinityHeroIds: ["demetria"],
    effectSuggestion: "Crise de longa duração; falha pode manter pessoas isoladas e bloquear rota estratégica.",
    designIntent: "Crise de Terra/estrutura: Demétria deve ser uma das melhores respostas contextuais; FOR/VIG dominam e reconhecimento permanece como capacidade complementar.",
  },
  {
    id: "pool-c-11",
    caseCode: "C-11",
    tier: "crisis",
    title: "Evacuação em Massa por Ameaça Incerta",
    district: "Leste",
    priority: "P1",
    reliability: "Baixa",
    description: "Alertas contraditórios provocaram evacuação espontânea de vários quarteirões. Há relatos de uma ameaça real, mas sua natureza e localização ainda não foram confirmadas.",
    recommendedTags: ["reconhecimento", "controle", "resgate"],
    attributeWeights: { intelligence: 3, charisma: 3, agility: 2 },
    spawnMinute: 0,
    deadlineMinutes: 48,
    missionDurationMinutes: 124,
    risk: "Alto",
    minDay: 7,
    weight: 1,
    cooldownDays: 20,
    powerAffinityHeroIds: [],
    effectSuggestion: "Falha gera pânico, congestionamento e pode ocultar a ameaça real. Boa base para informação imperfeita futura.",
    designIntent: "Crise de CAR/INT; importante para não concentrar late game apenas em FOR/VIG.",
  },
  {
    id: "pool-c-12",
    caseCode: "C-12",
    tier: "crisis",
    title: "Ataque Simultâneo a Infraestrutura Municipal",
    district: "Norte",
    priority: "P1",
    reliability: "Baixa",
    description: "Três instalações municipais reportam intrusões quase ao mesmo tempo. Ainda não está claro qual é o alvo principal e quais pontos servem apenas como distração.",
    recommendedTags: ["reconhecimento", "interceptacao", "combate", "controle"],
    attributeWeights: { charisma: 3, agility: 2, intelligence: 2 },
    spawnMinute: 0,
    deadlineMinutes: 42,
    missionDurationMinutes: 134,
    risk: "Alto",
    minDay: 8,
    weight: 1,
    cooldownDays: 24,
    powerAffinityHeroIds: ["eros"],
    effectSuggestion: "Caso de decisão sob informação incompleta. Falha pode permitir que o alvo principal seja atingido.",
    designIntent: "Foco CAR/coordenação sob múltiplas frentes: Eros ganha valor para comunicação, reconhecimento aéreo e reposicionamento, sem eliminar soluções alternativas.",
  },
];

export const caseById = Object.fromEntries(caseBank.map((incident) => [incident.id, incident])) as Record<string, Incident>;
