import type { Incident } from "@/game/types";

// spawnMinute = minutos após 08:00. Os chamados se sobrepõem de propósito.
// Os cinco atributos pessoais não substituem especialidades/poderes: tags continuam sendo parte central da adequação.
export const incidents: Incident[] = [
  { id:"inc-001", title:"Incêndio no Edifício Aurora", district:"Centro", priority:"P1", reliability:"Média", description:"Fumaça densa no 7º andar. Civis ainda podem estar presos e a estrutura começou a apresentar deformações pelo calor.", recommendedTags:["resgate","controle","mobilidade"], attributeWeights:{ intelligence:3, vigor:2, agility:2 }, spawnMinute:8, deadlineMinutes:54, missionDurationMinutes:96, risk:"Alto" },
  { id:"inc-002", title:"Perseguição na Linha Norte", district:"Norte", priority:"P2", reliability:"Alta", description:"Suspeito com habilidade desconhecida foge por vias elevadas e muda de rota constantemente.", recommendedTags:["velocidade","interceptacao","mobilidade"], attributeWeights:{ agility:3, intelligence:2, vigor:1 }, spawnMinute:34, deadlineMinutes:62, missionDurationMinutes:72, risk:"Médio" },
  { id:"inc-003", title:"Desabamento no Mercado Velho", district:"Oeste", priority:"P1", reliability:"Alta", description:"Parte da cobertura cedeu durante horário de pico. Há pessoas soterradas e risco de novos colapsos.", recommendedTags:["resgate","contenção","resistencia"], attributeWeights:{ strength:3, vigor:3, intelligence:1 }, spawnMinute:92, deadlineMinutes:70, missionDurationMinutes:118, risk:"Alto" },
  { id:"inc-004", title:"Pane Energética no Hospital", district:"Centro", priority:"P2", reliability:"Baixa", description:"Oscilações elétricas afetaram equipamentos críticos. O gerador auxiliar também apresenta comportamento irregular.", recommendedTags:["energia","precisao","controle"], attributeWeights:{ intelligence:3, agility:1, vigor:1 }, spawnMinute:118, deadlineMinutes:76, missionDurationMinutes:84, risk:"Médio" },
  { id:"inc-005", title:"Reféns no Terminal Sul", district:"Sul", priority:"P1", reliability:"Média", description:"Grupo armado mantém passageiros em uma plataforma subterrânea. Há relatos conflitantes sobre a quantidade de agressores.", recommendedTags:["interceptacao","controle","precisao"], attributeWeights:{ intelligence:3, charisma:2, agility:2 }, spawnMinute:205, deadlineMinutes:58, missionDurationMinutes:105, risk:"Alto" },
  { id:"inc-006", title:"Enchente na Baixada Leste", district:"Leste", priority:"P2", reliability:"Alta", description:"A água sobe rapidamente e moradores estão isolados em telhados. A correnteza dificulta aproximação terrestre.", recommendedTags:["resgate","mobilidade","controle"], attributeWeights:{ vigor:2, agility:2, intelligence:2 }, spawnMinute:226, deadlineMinutes:94, missionDurationMinutes:126, risk:"Médio" },
  { id:"inc-007", title:"Ataque ao Depósito Municipal", district:"Norte", priority:"P3", reliability:"Média", description:"Invasores super-humanos tentam roubar artefatos apreendidos. O objetivo exato ainda não está claro.", recommendedTags:["combate","potencia","reconhecimento"], attributeWeights:{ strength:3, intelligence:2, vigor:2 }, spawnMinute:310, deadlineMinutes:110, missionDurationMinutes:92, risk:"Médio" },
  { id:"inc-008", title:"Trem Elevado Fora de Controle", district:"Centro", priority:"P1", reliability:"Alta", description:"Uma composição sem frenagem se aproxima de duas estações lotadas. O tempo de intervenção é curto.", recommendedTags:["mobilidade","controle","potencia"], attributeWeights:{ agility:3, intelligence:3, strength:1 }, spawnMinute:372, deadlineMinutes:48, missionDurationMinutes:90, risk:"Alto" },
  { id:"inc-009", title:"Evacuação da Torre Prisma", district:"Oeste", priority:"P2", reliability:"Baixa", description:"Alarme estrutural e relatos conflitantes apontam uma anomalia no subsolo. Parte dos ocupantes se recusa a evacuar.", recommendedTags:["resgate","reconhecimento","contenção"], attributeWeights:{ intelligence:3, charisma:2, vigor:1 }, spawnMinute:430, deadlineMinutes:88, missionDurationMinutes:108, risk:"Médio" },
  { id:"inc-010", title:"Confronto na Praça Cívica", district:"Centro", priority:"P1", reliability:"Média", description:"Dois super-humanos em conflito colocam civis e prédios públicos em risco. A multidão dificulta uma resposta agressiva.", recommendedTags:["controle","combate","resgate"], attributeWeights:{ charisma:2, intelligence:2, strength:2, agility:1 }, spawnMinute:486, deadlineMinutes:68, missionDurationMinutes:96, risk:"Alto" }
];
