import type { DialogueChoice, DialogueMessage, DialogueScene } from "@/game/types";

function c(id:string,text:string,response:string,flag:string,romanceAffinity:100|50|30,delta:DialogueChoice["delta"],extras:Partial<DialogueChoice>={}):DialogueChoice {
  return { id, text, response, flag, romanceAffinity, delta, ...extras };
}

const photoCollege: DialogueMessage[] = [{ direction:"incoming", image:"/nexo/demetria/chat-1-faculdade.webp", imageAlt:"Foto enviada por Demétria a caminho da faculdade." }];
const photoGym: DialogueMessage[] = [{ direction:"incoming", image:"/nexo/demetria/chat-2-academia.webp", imageAlt:"Foto enviada por Demétria na academia." }];
const photoDate2: DialogueMessage[] = [{ direction:"incoming", image:"/nexo/demetria/chat-3-date2.webp", imageAlt:"Foto enviada por Demétria antes do segundo encontro." }];

const day1: DialogueScene = {
  day:1,id:"dia1-demetria-pos-expediente",characterId:"demetria",speaker:"Demétria",timeLabel:"19:24 · NEXO",opening:"Oii, você é {{playerName}}, né? Começou hoje como Analista?",
  availability:{minDay:1,maxDay:1},completionFlag:"scene:dia1-demetria-pos-expediente:complete",
  choices:[
    c("base","Oii, sim comecei hoje, já ia te chamar para conversar mesmo.","Imaginei kkkk sempre bom conhecer mais sobre as pessoas na qual estamos trabalhando.","demetria:r1:t1:50",50,{trust:1}),
    c("alternativa","Oii, sou sim, você chegou primeiro, já estava pensando em te chamar.","Imaginei kkkk sempre bom conhecer mais sobre as pessoas na qual estamos trabalhando.","demetria:r1:t1:30",30,{respect:1}),
    c("aberta","Sim, comecei hoje! Bom que você me chamou, queria conhecer melhor todo mundo.","Imaginei kkkk sempre bom conhecer mais sobre as pessoas na qual estamos trabalhando.","demetria:r1:t1:100",100,{intimacy:1}),
  ],followUps:[
    {id:"demetria:r1:t2",incoming:"",choices:[
      c("base","Com toda certeza, então, me conta mais sobre você.","Ok, meus poderes são relacionados a tudo que envolve terra em geral, mas gosto da parte mais prática e física dela, então sou bastante forte e resistente, então combate físico é a minha praia,cresci em uma família muito envolvida em política, mas não tenho paciência alguma para essas questões, mas gosto da parte investigativa, por isso além de heroína curso Perícia Criminal durante a noite.","demetria:r1:t2:50",50,{trust:1}),
      c("alternativa","Concordo, então aproveitando, quero saber mais sobre você.","Ok, meus poderes são relacionados a tudo que envolve terra em geral, mas gosto da parte mais prática e física dela, então sou bastante forte e resistente, então combate físico é a minha praia,cresci em uma família muito envolvida em política, mas não tenho paciência alguma para essas questões, mas gosto da parte investigativa, por isso além de heroína curso Perícia Criminal durante a noite.","demetria:r1:t2:30",30,{respect:1}),
      c("aberta","Faz sentido, principalmente trabalhando juntos. O que você pode me contar sobre você?","Ok, meus poderes são relacionados a tudo que envolve terra em geral, mas gosto da parte mais prática e física dela, então sou bastante forte e resistente, então combate físico é a minha praia,cresci em uma família muito envolvida em política, mas não tenho paciência alguma para essas questões, mas gosto da parte investigativa, por isso além de heroína curso Perícia Criminal durante a noite.","demetria:r1:t2:100",100,{intimacy:1}),
    ]},
    {id:"demetria:r1:t3",incoming:"",choices:[
      c("base","Caramba, consegue administrar muito bem seu tempo, que demais. Agradeço muito, vai ajudar bastante!","Nada, {{playerForm:fofo|fofa|fofe}}, qualquer coisa pode me chamar… Tchau tchau!","demetria:r1:t3:50",50,{trust:1}),
      c("alternativa","Caramba, heroína, Perícia Criminal e ainda trabalhando aqui, é bastante coisa. Muito bom saber disso, vai ajudar bastante!","Nada, {{playerForm:fofo|fofa|fofe}}, qualquer coisa pode me chamar… Tchau tchau!","demetria:r1:t3:30",30,{respect:1}),
      c("aberta","Nossa, então você consegue juntar bem a parte de investigação com a parte física. Já deu para entender bastante sobre você.","Nada, {{playerForm:fofo|fofa|fofe}}, qualquer coisa pode me chamar… Tchau tchau!","demetria:r1:t3:100",100,{intimacy:1}),
    ]},
    {id:"demetria:r1:t4",incoming:"",choices:[
      c("base","Até amanhã!","","demetria:r1:t4:50",50,{trust:1}),c("alternativa","Pode deixar, até amanhã!","","demetria:r1:t4:30",30,{respect:1}),c("aberta","Combinado, a gente se fala amanhã!","","demetria:r1:t4:100",100,{intimacy:1}),
    ]},
  ]
};

const day2: DialogueScene = {
  day:2,id:"placeholder-dia2-demetria",characterId:"demetria",speaker:"Demétria",timeLabel:"19:18 · NEXO",opening:"Tive que sair mais cedo hoje, pois tenho prova, mas parabéns por hoje, foi muito bom!",availability:{minDay:2,maxDay:2},completionFlag:"scene:placeholder-dia2-demetria:complete",
  choices:[c("base","Agradeço muito! Você também foi muito boa hoje!","Acho que vamos nos dar bem, acho que a gente combina no jeito de resolver as coisas.","demetria:r2:t1:50",50,{trust:1}),c("alternativa","Valeu! Você também mandou muito bem hoje!","Acho que vamos nos dar bem, acho que a gente combina no jeito de resolver as coisas.","demetria:r2:t1:30",30,{respect:1}),c("aberta","Agradeço! E você também foi muito bem hoje!","Acho que vamos nos dar bem, acho que a gente combina no jeito de resolver as coisas.","demetria:r2:t1:100",100,{intimacy:1})],
  followUps:[
    {id:"demetria:r2:t2",incoming:"",choices:[c("base","Simm, aliás como você lida com tudo isso?","Correndo kkkk","demetria:r2:t2:50",50,{trust:1},{afterResponse:photoCollege}),c("alternativa","Também acho, parece que nosso jeito de trabalhar combina mesmo. Como você consegue conciliar tudo?","Correndo kkkk","demetria:r2:t2:30",30,{respect:1},{afterResponse:photoCollege}),c("aberta","Simm, também tive essa impressão. Mas como você administra Agência e faculdade?","Correndo kkkk","demetria:r2:t2:100",100,{intimacy:1},{afterResponse:photoCollege})]},
    {id:"demetria:r2:t3",incoming:"",choices:[c("base","Justo, boa sorte na prova!","Obrigada, {{playerForm:fofo|fofa|fofe}} <3\nAcho que corri demais e cheguei meio cedo…","demetria:r2:t3:50",50,{trust:1}),c("alternativa","Kkkkk justo, então boa sorte na prova!","Obrigada, {{playerForm:fofo|fofa|fofe}} <3\nAcho que corri demais e cheguei meio cedo…","demetria:r2:t3:30",30,{respect:1}),c("aberta","Pelo visto correndo mesmo kkkk, boa sorte na prova!","Obrigada, {{playerForm:fofo|fofa|fofe}} <3\nAcho que corri demais e cheguei meio cedo…","demetria:r2:t3:100",100,{intimacy:1})]},
    {id:"demetria:r2:t4",incoming:"",choices:[c("base","Da pra revisar as coisas então.","Acho que nem precisa, estou bem preparada para a prova, o conteúdo é sobre Criminalística e Análise de Local de Crime.","demetria:r2:t4:50",50,{trust:1}),c("alternativa","Pelo menos agora dá para revisar alguma coisa.","Acho que nem precisa, estou bem preparada para a prova, o conteúdo é sobre Criminalística e Análise de Local de Crime.","demetria:r2:t4:30",30,{respect:1}),c("aberta","Melhor chegar cedo, dá para aproveitar e revisar.","Acho que nem precisa, estou bem preparada para a prova, o conteúdo é sobre Criminalística e Análise de Local de Crime.","demetria:r2:t4:100",100,{intimacy:1})]},
    {id:"demetria:r2:t5",incoming:"",choices:[c("base","Tive um pouco disso na minha faculdade também.","Fez curso de Administração Heroica?","demetria:r2:t5:50",50,{trust:1}),c("alternativa","Já vi um pouco sobre isso na minha faculdade também.","Fez curso de Administração Heroica?","demetria:r2:t5:30",30,{respect:1}),c("aberta","Criminalística eu conheço um pouco, tive contato com isso na faculdade.","Fez curso de Administração Heroica?","demetria:r2:t5:100",100,{intimacy:1})]},
    {id:"demetria:r2:t6",incoming:"",choices:[c("base","Sim sim, pesquisou sobre mim é?","Talvez kkkk como eu disse ontem é bom saber com quem está trabalhando né 😊","demetria:r2:t6:50",50,{trust:1}),c("alternativa","Fiz sim, como você descobriu?","Talvez kkkk como eu disse ontem é bom saber com quem está trabalhando né 😊","demetria:r2:t6:30",30,{respect:1}),c("aberta","Sim kkkk, então você andou pesquisando sobre mim?","Talvez kkkk como eu disse ontem é bom saber com quem está trabalhando né 😊","demetria:r2:t6:100",100,{intimacy:1})]},
    {id:"demetria:r2:t7",incoming:"",choices:[c("base","Faz todo sentido, mesmo.","Enfim deu o horário, tenho que ir, tchau!","demetria:r2:t7:50",50,{trust:1}),c("alternativa","Justo kkkk, você realmente leva isso a sério.","Enfim deu o horário, tenho que ir, tchau!","demetria:r2:t7:30",30,{respect:1}),c("aberta","Faz sentido, vou ter que começar a pesquisar sobre você também então.","Enfim deu o horário, tenho que ir, tchau!","demetria:r2:t7:100",100,{intimacy:1})]},
    {id:"demetria:r2:t8",incoming:"",choices:[c("base","Tchau! Boa prova!","<3","demetria:r2:t8:50",50,{trust:1}),c("alternativa","Vai lá, boa prova!","<3","demetria:r2:t8:30",30,{respect:1}),c("aberta","Tchau! Depois me conta como foi!","<3","demetria:r2:t8:100",100,{intimacy:1})]},
  ]
};

const day3: DialogueScene = {day:3,id:"placeholder-dia3-demetria",characterId:"demetria",speaker:"Demétria",timeLabel:"19:26 · NEXO",opening:"Eii",availability:{minDay:3,maxDay:3},completionFlag:"scene:placeholder-dia3-demetria:complete",choices:[c("base","Oii","Vou fazer uma apresentação de um trabalho que eu fiz, vai ser sobre Reconstrução Dinâmica de um Local de Crime a partir de Vestígios, não sei é algo que lhe interessa mas se quiser ir está convidado, ta?","demetria:r3:t1:50",50,{trust:1}),c("alternativa","Eii, tudo bem?","Vou fazer uma apresentação de um trabalho que eu fiz, vai ser sobre Reconstrução Dinâmica de um Local de Crime a partir de Vestígios, não sei é algo que lhe interessa mas se quiser ir está convidado, ta?","demetria:r3:t1:30",30,{respect:1}),c("aberta","Opa, fala comigo.","Vou fazer uma apresentação de um trabalho que eu fiz, vai ser sobre Reconstrução Dinâmica de um Local de Crime a partir de Vestígios, não sei é algo que lhe interessa mas se quiser ir está convidado, ta?","demetria:r3:t1:100",100,{intimacy:1})],followUps:[
{id:"demetria:r3:t2",incoming:"",choices:[c("base","Claro! Vou sim! É na Universidade Atlas?","Isso! Só vir aqui na UA, próximo ao bloco de Direito tem um centro de eventos onde acontecem essas apresentações livres.","demetria:r3:t2:50",50,{trust:1}),c("alternativa","Parece interessante, quero ir sim! Vai ser na Universidade Atlas?","Isso! Só vir aqui na UA, próximo ao bloco de Direito tem um centro de eventos onde acontecem essas apresentações livres.","demetria:r3:t2:30",30,{respect:1}),c("aberta","Quero sim, ainda mais depois de você falar tanto sobre o curso. É lá na Universidade Atlas?","Isso! Só vir aqui na UA, próximo ao bloco de Direito tem um centro de eventos onde acontecem essas apresentações livres.","demetria:r3:t2:100",100,{intimacy:1})]},
{id:"demetria:r3:t3",incoming:"",choices:[c("base","Beleza, finalizando o relatório já vou direto pra lá.","Oba! Te espero então! Beijo!","demetria:r3:outing:50",50,{trust:1,intimacy:1},{exclusiveOutingDay:3,vnSceneId:"outing-day3-demetria"}),c("alternativa","Certo, assim que terminar o relatório aqui eu vou para lá.","Oba! Te espero então! Beijo!","demetria:r3:outing:30",30,{trust:1},{exclusiveOutingDay:3,vnSceneId:"outing-day3-demetria"}),c("aberta","Combinado, vou finalizar o que tenho aqui e já apareço por lá.","Oba! Te espero então! Beijo!","demetria:r3:outing:100",100,{intimacy:1,attraction:2},{exclusiveOutingDay:3,vnSceneId:"outing-day3-demetria"})]}
]};

const day4: DialogueScene = {day:4,id:"placeholder-dia4-demetria",characterId:"demetria",speaker:"Demétria",timeLabel:"19:11 · NEXO",openingOutgoing:"Oie",opening:"Oi {{playerForm:lindo|linda|linde}}, como você tá? Foi tranquilo hoje",availability:{minDay:4,maxDay:4},completionFlag:"scene:placeholder-dia4-demetria:complete",choices:[c("base","To bem, acho que vou finalizar rápido aqui hoje. Tá indo pra aula?","Nada, hoje acabou por não ter aula, professor tá doente, vou ter mais tempo para ir para a academia pelo menos.","demetria:r4:t1:50",50,{trust:1}),c("alternativa","Tô bem, hoje acho que termino tudo cedo. Vai para a faculdade agora?","Nada, hoje acabou por não ter aula, professor tá doente, vou ter mais tempo para ir para a academia pelo menos.","demetria:r4:t1:30",30,{respect:1}),c("aberta","Tudo tranquilo, acho que não vou demorar muito aqui hoje. Tem aula agora?","Nada, hoje acabou por não ter aula, professor tá doente, vou ter mais tempo para ir para a academia pelo menos.","demetria:r4:t1:100",100,{intimacy:1})],followUps:[
{id:"demetria:r4:t2",incoming:"",choices:[c("base","Sempre bom né, eu deveria começar a ir na academia aqui da agência, é bem cômodo.","É verdade, se quiser que eu te acompanhe só me chamar 😛","demetria:r4:t2:50",50,{trust:1}),c("alternativa","Pelo menos dá para aproveitar o tempo. Eu ainda quero começar a usar a academia aqui da Agência.","É verdade, se quiser que eu te acompanhe só me chamar 😛","demetria:r4:t2:30",30,{respect:1}),c("aberta","Boa, pelo menos ganhou mais tempo para treinar. Preciso começar a frequentar a academia daqui também.","É verdade, se quiser que eu te acompanhe só me chamar 😛","demetria:r4:t2:100",100,{intimacy:1})]},
{id:"demetria:r4:t3",incoming:"",choices:[c("base","Com certeza, assim que a chefia liberar meu Passe de Academia eu começo, prometo…","Vou cobrar ein.","demetria:r4:t3:50",50,{trust:1},{afterResponse:photoGym}),c("alternativa","Fechado, quando meu Passe de Academia sair eu te chamo.","Vou cobrar ein.","demetria:r4:t3:30",30,{respect:1},{afterResponse:photoGym}),c("aberta","Cuidado que eu vou aceitar essa oferta, só falta liberarem meu Passe de Academia.","Vou cobrar ein.","demetria:r4:t3:100",100,{intimacy:1,attraction:1},{afterResponse:photoGym})]},
{id:"demetria:r4:t4",incoming:"Vou fazer meu treino então, beijo!",choices:[c("base","Beijo, até amanhã!","","demetria:r4:t4:50",50,{trust:1}),c("alternativa","Bom treino, até amanhã!","","demetria:r4:t4:30",30,{respect:1}),c("aberta","Vai lá, bom treino! Até amanhã!","","demetria:r4:t4:100",100,{intimacy:1})]}
]};

const day5: DialogueScene = {day:5,id:"placeholder-dia5-demetria",characterId:"demetria",speaker:"Demétria",timeLabel:"19:22 · NEXO",opening:"Terrível hoje, nossa senhora…",availability:{minDay:5,maxDay:5},completionFlag:"scene:placeholder-dia5-demetria:complete",choices:[c("base","O caso da prefeitura de hoje?","Sim.","demetria:r5:t1:50",50,{trust:1}),c("alternativa","Por causa do caso da prefeitura?","Sim.","demetria:r5:t1:30",30,{respect:1}),c("aberta","Imagino que seja sobre o que aconteceu na prefeitura hoje.","Sim.","demetria:r5:t1:100",100,{intimacy:1})],followUps:[
{id:"demetria:r5:t2",incoming:"",choices:[c("base","Entendível…","Juro como pode minha mãe e minha irmã me atrapalhando enquanto eu estou tentando resolver um caso com gente armada e reféns, do lado delas e elas me enchendo tentando me dizer o que fazer, por isso sempre quis ficar longe disso.","demetria:r5:t2:50",50,{trust:1}),c("alternativa","Imaginei…","Juro como pode minha mãe e minha irmã me atrapalhando enquanto eu estou tentando resolver um caso com gente armada e reféns, do lado delas e elas me enchendo tentando me dizer o que fazer, por isso sempre quis ficar longe disso.","demetria:r5:t2:30",30,{respect:1}),c("aberta","É, foi complicado mesmo…","Juro como pode minha mãe e minha irmã me atrapalhando enquanto eu estou tentando resolver um caso com gente armada e reféns, do lado delas e elas me enchendo tentando me dizer o que fazer, por isso sempre quis ficar longe disso.","demetria:r5:t2:100",100,{intimacy:1})]},
{id:"demetria:r5:t3",incoming:"",choices:[c("base","No fim deu tudo certo pelo menos, você conseguiu manter o controle e resolver a situação, poderia ser pior.","Mas poderia ter sido melhor…","demetria:r5:t3:50",50,{trust:1}),c("alternativa","Pelo menos você conseguiu manter o controle da situação e resolver tudo no final, mesmo com elas ali.","Mas poderia ter sido melhor…","demetria:r5:t3:30",30,{respect:1}),c("aberta","Foi muita coisa para lidar ao mesmo tempo, mas você conseguiu resolver a situação. Isso também conta.","Mas poderia ter sido melhor…","demetria:r5:t3:100",100,{intimacy:1})]},
{id:"demetria:r5:t4",incoming:"",choices:[c("base","Calma, tá tudo bem, aqui não precisamos nos preocupar com elas atrapalhando nada, é só a gente aqui da agência e raros momentos com uns famosos malucos mas nada demais sabe.","Eu sei, é complicado mas não posso deixar elas entrarem na minha cabeça e me deixar mal. Vou tentar me distrair com algo.","demetria:r5:t4:50",50,{trust:1}),c("alternativa","Eu sei, mas aqui na Agência você não precisa ficar se preocupando com elas interferindo. Aqui é a gente tentando resolver as coisas juntos.","Eu sei, é complicado mas não posso deixar elas entrarem na minha cabeça e me deixar mal. Vou tentar me distrair com algo.","demetria:r5:t4:30",30,{respect:1}),c("aberta","Poderia, mas não precisa carregar isso agora. Aqui você tem espaço para trabalhar sem elas tentando controlar tudo.","Eu sei, é complicado mas não posso deixar elas entrarem na minha cabeça e me deixar mal. Vou tentar me distrair com algo.","demetria:r5:t4:100",100,{intimacy:1})]},
{id:"demetria:r5:t5",incoming:"",choices:[c("base","Isso, tenta se distrair, assiste um filme, um documentário, algo assim. Focar em outras coisas.","Enfim, vou indo por agora, tchau tchau!","demetria:r5:t5:50",50,{trust:1}),c("alternativa","Faz isso, procura alguma coisa para assistir e descansa a cabeça um pouco.","Enfim, vou indo por agora, tchau tchau!","demetria:r5:t5:30",30,{respect:1}),c("aberta","Boa, tenta ocupar a cabeça com outra coisa por hoje. Amanhã você pensa nisso com mais calma.","Enfim, vou indo por agora, tchau tchau!","demetria:r5:t5:100",100,{intimacy:1})]},
{id:"demetria:r5:t6",incoming:"",choices:[c("base","Tchau, Fica bem!","","demetria:r5:t6:50",50,{trust:1}),c("alternativa","Tchau, se cuida!","","demetria:r5:t6:30",30,{respect:1}),c("aberta","Até amanhã, tenta descansar um pouco!","","demetria:r5:t6:100",100,{intimacy:1})]}
]};

const day6: DialogueScene = {day:6,id:"placeholder-dia6-demetria",characterId:"demetria",speaker:"Demétria",timeLabel:"19:34 · NEXO",opening:"Chegou em casa?",availability:{minDay:6,maxDay:6},completionFlag:"scene:placeholder-dia6-demetria:complete",choices:[c("base","Cheguei sim, acabei de sair do banho.","Belezinha.\nSabe eu to montando uma apresentação nova, precisava de alguém para ver como ta indo.\nE eu quero você.","demetria:r6:t1:50",50,{trust:1}),c("alternativa","Cheguei agora pouco, por quê?","Belezinha.\nSabe eu to montando uma apresentação nova, precisava de alguém para ver como ta indo.\nE eu quero você.","demetria:r6:t1:30",30,{respect:1}),c("aberta","Sim, já estou em casa. Aconteceu alguma coisa?","Belezinha.\nSabe eu to montando uma apresentação nova, precisava de alguém para ver como ta indo.\nE eu quero você.","demetria:r6:t1:100",100,{intimacy:1})],followUps:[
{id:"demetria:r6:t2",incoming:"",choices:[c("base","Eu? Será que vou saber dar uma boa review?","Você sim, quero ver você {{playerForm:hipnotizado|hipnotizada|hipnotizade}} de novo…","demetria:r6:t2:50",50,{trust:1}),c("alternativa","Eu especificamente? Posso tentar, mas não sei se vou saber avaliar direito.","Você sim, quero ver você {{playerForm:hipnotizado|hipnotizada|hipnotizade}} de novo…","demetria:r6:t2:30",30,{respect:1}),c("aberta","Desse jeito parece até que você já decidiu que eu vou kkkk.","Você sim, quero ver você {{playerForm:hipnotizado|hipnotizada|hipnotizade}} de novo…","demetria:r6:t2:100",100,{intimacy:1,attraction:1})]},
{id:"demetria:r6:t3",incoming:"",choices:[c("base","Vou me esforçar para entender tudo então.","Consegue vir agora?","demetria:r6:t3:50",50,{trust:1},{afterResponse:photoDate2}),c("alternativa","Aí você tá aumentando bastante a expectativa kkkk.","Consegue vir agora?","demetria:r6:t3:30",30,{respect:1},{afterResponse:photoDate2}),c("aberta","Desse jeito vai ficar difícil prestar atenção só na apresentação.","Consegue vir agora?","demetria:r6:t3:100",100,{intimacy:1,attraction:2},{afterResponse:photoDate2})]},
{id:"demetria:r6:t4",incoming:"",choices:[c("base","Sim, senhora. Estou a caminho.","Vou me arrumar então 😊, quando chegar avisa.","demetria:r6:t4:50",50,{trust:1,intimacy:1}),c("alternativa","Consigo sim, já estou indo.","Vou me arrumar então 😊, quando chegar avisa.","demetria:r6:t4:30",30,{trust:1}),c("aberta","Tá bom, você me convenceu. Estou a caminho.","Vou me arrumar então 😊, quando chegar avisa.","demetria:r6:t4:100",100,{intimacy:1,attraction:2})]},
{id:"demetria:r6:t5",incoming:"",choices:[c("base","Cheguei.","","demetria:r6:outing:50",50,{trust:1,intimacy:1},{exclusiveOutingDay:6,vnSceneId:"outing-day6-demetria"}),c("alternativa","Cheguei, estou aqui fora.","","demetria:r6:outing:30",30,{trust:1},{exclusiveOutingDay:6,vnSceneId:"outing-day6-demetria"}),c("aberta","Cheguei. Pode abrir pra mim 😊","","demetria:r6:outing:100",100,{intimacy:1,attraction:2},{exclusiveOutingDay:6,vnSceneId:"outing-day6-demetria"})]}
]};

export const demetriaPostShiftScenes: DialogueScene[] = [day1,day2,day3,day4,day5,day6];
