export const PROGRESSIVE_TUTORIAL_FLAGS = {
  development: "tutorial:development:seen",
  technique: "tutorial:development:technique:seen",
  attribute: "tutorial:development:attribute:seen",
  mastery: "tutorial:development:mastery:seen",
  resonance: "tutorial:dispatch:resonance:seen",
  combo: "tutorial:dispatch:combo:seen",
  condition: "tutorial:dispatch:condition:seen",
  postShiftNexo: "tutorial:nexo:post-shift:seen",
  date: "tutorial:nexo:date:seen",
} as const;

export const progressiveTutorialCopy = {
  development: {
    eyebrow: "EDISON · DESENVOLVIMENTO",
    progressLabel: "1/3",
    title: "A experiência virou uma decisão",
    body: "Agentes marcados com UP possuem uma evolução pendente. Abra um deles para resolver o próximo marco antes de seguir para a noite.",
    targetLabel: "Selecione um agente marcado com UP",
    tone: "orientation" as const,
  },
  technique: {
    eyebrow: "EDISON · DESENVOLVIMENTO",
    progressLabel: "2/3",
    title: "Este nível libera uma nova capacidade",
    body: "Compare as opções. Técnicas podem adicionar capacidades úteis em futuros despachos; a escolha passa a valer no próximo expediente.",
    targetLabel: "Escolha uma técnica para concluir o nível",
    tone: "discovery" as const,
  },
  attribute: {
    eyebrow: "EDISON · DESENVOLVIMENTO",
    progressLabel: "2/3",
    title: "Este nível concede +1 atributo",
    body: "Use + para pré-visualizar a mudança no radar. Você ainda pode trocar a escolha antes de confirmar.",
    targetLabel: "Aplique +1 e confirme quando estiver satisfeito",
    tone: "orientation" as const,
  },
  mastery: {
    eyebrow: "EDISON · MAESTRIA",
    progressLabel: "3/3",
    title: "XP continua útil depois do nível 6",
    body: "A progressão principal terminou, mas XP adicional aumenta a Maestria até o rank 5 e melhora a consistência do agente em operações solo.",
    targetLabel: "Confira o rank de Maestria",
    tone: "success" as const,
  },
  resonance: {
    eyebrow: "EDISON · EQUIPE",
    title: "Observe a Ressonância da equipe",
    body: "Você montou uma equipe com mais de um agente. Nem toda dupla trabalha com a mesma sintonia; composição importa mais do que quantidade.",
    targetLabel: "Confira Ressonância e cobertura antes de despachar",
    tone: "orientation" as const,
  },
  combo: {
    eyebrow: "EDISON · COMBO DESCOBERTO",
    title: "Essa dupla possui uma sinergia especial",
    body: "O briefing identificou um Combo. Ele concede uma vantagem própria a essa composição; não é necessário usar sempre a mesma dupla.",
    targetLabel: "Confira o efeito destacado no briefing",
    tone: "discovery" as const,
  },
  condition: {
    eyebrow: "EDISON · ATENÇÃO",
    title: "Condição também entra na decisão",
    body: "Um agente selecionado está cansado ou machucado. Se Vida ou Energia chegar a zero, ele fica indisponível até o dia seguinte.",
    targetLabel: "Revise a condição antes de confirmar a equipe",
    tone: "attention" as const,
  },
  postShiftNexo: {
    eyebrow: "EDISON · PÓS-EXPEDIENTE",
    title: "O NEXO não é uma escolha única",
    body: "Você pode conversar com todos os contatos disponíveis nesta noite, se quiser. Não é obrigatório falar com ninguém; para avançar uma rota, abra o contato e envie a mensagem ou resposta disponível. Conversar com alguém não bloqueia os demais.",
    targetLabel: "Abra qualquer contato e envie/responda para avançar a conversa",
    tone: "orientation" as const,
  },
  date: {
    eyebrow: "EDISON · CONVITE",
    title: "Um encontro é uma ação separada",
    body: "O convite permanece no NEXO até você decidir ir. Apenas uma saída presencial pode ser escolhida por noite.",
    targetLabel: "Abra a conversa com DATE e use IR PARA ENCONTRO",
    tone: "discovery" as const,
  },
} as const;
