import { HeroRadar } from "@/components/HeroRadar";
import { getHeroPortrait } from "@/game/data/heroPortraits";
import { getEnergyState, getHealthState, getMaxEnergy, getMaxHealth } from "@/game/simulation/heroState";
import type { OperationalHero } from "@/game/types";

const attributeLabels: Record<string,string> = { strength:"Força", agility:"Agilidade", charisma:"Carisma", intelligence:"Inteligência", vigor:"Vigor" };

export function HeroDossierModal({ hero, onClose }: { hero: OperationalHero; onClose: () => void }) {
  return <div className="opsModalBackdrop heroInfoBackdrop" onMouseDown={onClose}><section className="heroInfoModal heroInfoModalClean" role="dialog" aria-modal="true" aria-labelledby="hero-dossier-title" onMouseDown={(event)=>event.stopPropagation()}>
    <button className="modalClose heroInfoClose" onClick={onClose} aria-label="Fechar dossiê">×</button>
    <div className="heroInfoBody heroInfoBodyClean">
      <aside className="heroIdentity heroIdentityClean"><span className="eyebrow">DOSSIÊ DE AGENTE</span><div className="heroDossierPortrait">{getHeroPortrait(hero.id) ? <img src={getHeroPortrait(hero.id)!} alt={`Retrato de ${hero.name}`} /> : <span>{hero.name.slice(0,2).toUpperCase()}</span>}</div><h2 id="hero-dossier-title">{hero.name}</h2><p className="heroRoleLine">{hero.powerName} · {hero.className} / {hero.trail}</p><div className="heroBioFacts" aria-label="Dados físicos"><span><small>IDADE</small><strong>{hero.age} anos</strong></span><span><small>ALTURA</small><strong>{(hero.heightCm / 100).toFixed(2).replace(".", ",")} m</strong></span><span><small>PESO</small><strong>{hero.weightKg} kg</strong></span></div><div className="styleTags">{hero.style.map((tag)=><span key={tag}>{tag}</span>)}</div><p>{hero.profile}</p><div className="conditionPanel conditionVitals"><span><small>VIDA · {getHealthState(hero.health, getMaxHealth(hero.attributes))}</small><b>{hero.health}/{getMaxHealth(hero.attributes)}</b><i className="vitalTrack"><i className={`vitalFill health ${hero.health / getMaxHealth(hero.attributes) <= .35 ? "critical" : hero.health / getMaxHealth(hero.attributes) <= .65 ? "warning" : ""}`} style={{width:`${(hero.health/getMaxHealth(hero.attributes))*100}%`}} /></i></span><span><small>ENERGIA · {getEnergyState(hero.energy, getMaxEnergy(hero.attributes))}</small><b>{hero.energy}/{getMaxEnergy(hero.attributes)}</b><i className="vitalTrack"><i className={`vitalFill energy ${hero.energy / getMaxEnergy(hero.attributes) <= .35 ? "critical" : hero.energy / getMaxEnergy(hero.attributes) <= .65 ? "warning" : ""}`} style={{width:`${(hero.energy/getMaxEnergy(hero.attributes))*100}%`}} /></i></span></div></aside>
      <div className="heroCapabilities"><div className="heroStatHeader"><div><span className="sectionLabel">ATRIBUTOS PESSOAIS</span><strong>NÍVEL {hero.level}</strong><small>{hero.xp} XP</small></div><span>Escala fixa 1–5</span></div><HeroRadar attributes={hero.attributes} /><div className="attributeRows compactFive">{Object.entries(hero.attributes).map(([key,value])=><div key={key}><span>{attributeLabels[key]}</span><i><b style={{width:`${value*20}%`}} /></i><strong>{value}/5</strong></div>)}</div><div className="heroUnlockedDispatch"><span className="sectionLabel">TÉCNICAS ATIVAS NO DESPACHO</span>{hero.unlockedTechniqueIds.length ? <div>{hero.techniques.filter((technique)=>hero.unlockedTechniqueIds.includes(technique.id)).map((technique)=><span key={technique.id}><strong>{technique.name}</strong><small>{technique.grantedTags?.length ? `Capacidades adicionadas: ${technique.grantedTags.join(", ")}` : technique.description}</small></span>)}</div> : <p>Nenhuma técnica de progressão desbloqueada. Técnicas adicionam capacidades usadas na chance de missão.</p>}</div><div className="capabilityColumns"><div><span className="sectionLabel">PONTOS FORTES</span>{hero.strengths.map((item)=><p key={item}>+ {item}</p>)}</div><div><span className="sectionLabel">LIMITAÇÕES</span>{hero.limitations.map((item)=><p key={item}>! {item}</p>)}</div></div></div>
    </div>
  </section></div>;
}
